using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using UnityEngine;

namespace BandoWare.GameplayTags
{
   public static class GameplayTagManager
   {
      /// <summary>
      /// All tag definitions (including parent-tags).
      /// </summary>
      private static GameplayTagDefinition[] s_TagDefinitions;

      /// <summary>
      /// All custom defined tags (including parent-tags, excluding the none-tag), cached for easy-access.
      /// </summary>
      private static GameplayTag[] s_Tags;

      /// <summary>
      ///  Names of all defined tags (including parent-tags) pointing to their tag definition (for efficient hash-based access).
      /// </summary>
      private static Dictionary<string, GameplayTagDefinition> s_TagDefinitionsByName = new();

      /// <summary>
      /// Old names of all renamed tags, pointing to their currently valid tag definition (resolved potential chain of renames).
      /// </summary>
      private static Dictionary<string, GameplayTagDefinition> s_RenamedTagDefinitionsByOldName = new();

      private static bool s_IsInitialized;

      public static ReadOnlySpan<GameplayTag> GetAllTags()
      {
         InitializeIfNeeded();
         return new ReadOnlySpan<GameplayTag>(s_Tags);
      }

      /// <summary>
      /// Returns all tags that are children from any of the given filterTagNames.
      /// </summary>
      public static ReadOnlySpan<GameplayTag> GetAllTagsFiltered(GameplayTagFilter tagFilter)
      {
         InitializeIfNeeded();

         if (!tagFilter.HasFilterTags)
         {
            // No filters applied
            return new ReadOnlySpan<GameplayTag>(s_Tags);
         }

         List<GameplayTag> filteredTags = new();

         foreach (GameplayTag tag in s_Tags)
         {
            if (tagFilter.IncludesTag(tag))
            {
               filteredTags.Add(tag);
            }
         }

         return new ReadOnlySpan<GameplayTag>(filteredTags.ToArray());
      }

      internal static IReadOnlyDictionary<string, GameplayTagDefinition> GetTagDefinitionsByName()
      {
         InitializeIfNeeded();
         return s_TagDefinitionsByName;
      }

      internal static IReadOnlyDictionary<string, GameplayTagDefinition> GetRenamedTagDefinitionsByOldName()
      {
         InitializeIfNeeded();
         return s_RenamedTagDefinitionsByOldName;
      }

      internal static GameplayTagDefinition GetDefinitionFromRuntimeIndex(int runtimeIndex)
      {
         InitializeIfNeeded();
         return s_TagDefinitions[runtimeIndex];
      }

      public static GameplayTag RequestTag(string tagName)
      {
         if (string.IsNullOrEmpty(tagName))
         {
            return GameplayTag.None;
         }

         if (!TryGetDefinition(tagName, out GameplayTagDefinition definition))
         {
            Debug.LogWarning($"No tag registered with name \"{tagName}\".");
            return GameplayTag.None;
         }

         return definition.Tag;
      }

      public static List<GameplayTag> RequestTagsByName(params string[] tagNames)
      {
         List<GameplayTag> resultTags = new();

         foreach (string tagName in tagNames)
         {
            GameplayTag tag = RequestTag(tagName);
            if (tag.IsValid())
            {
               resultTags.Add(tag);
            }
         }

         return resultTags;
      }

      public static List<GameplayTag> RequestTagsByType(params Type[] tagTypes)
      {
         List<GameplayTag> resultTags = new();

         foreach (Type type in tagTypes)
         {
            // Access the GameplayTag name directly from the type (generated by the code generator), via reflection
            MethodInfo method = type.GetMethod("Get", BindingFlags.Public | BindingFlags.Static);
            if (method != null)
            {
               GameplayTag tag = (GameplayTag)method.Invoke(null, null);
               if (tag.IsValid())
               {
                  resultTags.Add(tag);
               }
            }
         }

         return resultTags;
      }

      internal static bool IsTagForTestingOnly(string tagName)
      {
         return tagName.StartsWith("Test.") || tagName.Equals("Test");
      }

      private static bool TryGetDefinition(string tagName, out GameplayTagDefinition definition)
      {
         InitializeIfNeeded();
         return s_TagDefinitionsByName.TryGetValue(tagName, out definition) || s_RenamedTagDefinitionsByOldName.TryGetValue(tagName, out definition);
      }

      private static void InitializeIfNeeded()
      {
         if (s_IsInitialized)
            return;

         GameplayTagRegistrationContext context = new();
         IReadOnlyList<TagRenameEntry> tagRenameEntries = Array.Empty<TagRenameEntry>();

         // Register all tags and rename entries found in the generated TagConfig class.
         if (GameplayTagConfigBase.TryGetGeneratedGameplayTagConfig(out GameplayTagConfigBase tagConfig))
         {
            foreach (TagDefinitionEntry definitionEntry in tagConfig.GetGameplayTagDefinitionEntries())
            {
               try
               {
                  context.RegisterTag(definitionEntry.tagName, definitionEntry.description);
               }
               catch (Exception exception)
               {
                  Debug.LogError($"Failed to register tag {definitionEntry.tagName} from {tagConfig.GetType().FullName} with error: {exception.Message}");
               }
            }

            // Load all unique TagRenameEntries.
            tagRenameEntries = tagConfig.GetGameplayTagsRenameEntries();
         }

         // Register all tags found in any Assembly via GameplayTagAttribute.
         foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
         {
            foreach (GameplayTagAttribute attribute in assembly.GetCustomAttributes<GameplayTagAttribute>())
            {
               try
               {
                  context.RegisterTag(attribute.TagName, attribute.Description, attribute.Flags);
               }
               catch (Exception exception)
               {
                  Debug.LogError($"Failed to register tag {attribute.TagName} from assembly {assembly.FullName} with error: {exception.Message}");
               }
            }
         }

         s_TagDefinitions = context.GenerateDefinitions();

         // Skip the first tag definition which is the "None" tag.
         s_Tags = s_TagDefinitions.Select(definition => definition.Tag).Skip(1).ToArray();

         foreach (GameplayTagDefinition definition in s_TagDefinitions)
         {
            s_TagDefinitionsByName[definition.TagName] = definition;
            // TODO: include weather renamed or not 
         }

         // Remap the OldTagNames registered via TagRenameEntries to point at the TagDefinition of the NewTagName.
         // From newest (last) to oldest (first) rename entry.
         for (int i = tagRenameEntries.Count - 1; i >= 0; i--)
         {
            TagRenameEntry renameEntry = tagRenameEntries[i];

            if (s_TagDefinitionsByName.ContainsKey(renameEntry.oldTagName))
            {
               // OldName appears to be valid again, as it is included in the currently-defined tags
               continue;
            }

            // Resolve the renamed tag to its currently defined valid definition.
            // The newName could either be found in the standard definitions, or is a chain of multiple previous renames,
            // thus found in the RenamedTagDefinitions dictionary.
            // (this is also the reason why we iterate the renames from newest to oldest) 
            if (s_TagDefinitionsByName.TryGetValue(renameEntry.newTagName, out GameplayTagDefinition resolvedDefinition)
                || s_RenamedTagDefinitionsByOldName.TryGetValue(renameEntry.newTagName, out resolvedDefinition))
            {
               // Use TryAdd, so we don't accidentally override an already valid renamed Tag to Definition mapping
               if (!s_RenamedTagDefinitionsByOldName.TryAdd(renameEntry.oldTagName, resolvedDefinition)
                   && s_RenamedTagDefinitionsByOldName[renameEntry.oldTagName] != resolvedDefinition)
               {
                  Debug.LogWarning($"Invalid TagRenameEntry detected: OldTagName '{renameEntry.oldTagName}' was be renamed " +
                                   $"to '{renameEntry.newTagName}', but is already mapped to Definition of '{resolvedDefinition.TagName}'");
               }
            }
         }

         s_IsInitialized = true;
      }
   }
}